# Generated by Django 3.1.1 on 2020-12-18 00:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('banner', models.URLField(blank=True, max_length=500)),
                ('date_event', models.DateTimeField(auto_now_add=True)),
                ('date_pub', models.DateTimeField(default=django.utils.timezone.now)),
                ('chapter_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
