# Generated by Django 3.1.1 on 2020-12-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecon',
            name='slug',
        ),
    ]
