# Generated by Django 3.1.1 on 2020-12-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_lecon_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecon',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200, unique=True),
        ),
    ]
